# Generated by Django 4.2.1 on 2023-05-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldetail',
            name='hashed_url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
