# Generated by Django 4.2.1 on 2023-05-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_alter_urldetail_hashed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldetail',
            name='hashed_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
